### ISSUE TITLE
Potential oddities in string tests

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#93] opened 2021-01-28 20:37 UTC
For https://github.com/phetsims/QA/issues/600. @amanda-phet suggested a catch all issue with some oddities noticed with string tests.
Equal signs seem off center when strings are long:
<img width="380" alt="oddlongequal" src="https://user-images.githubusercontent.com/41024075/106195709-c0dd7300-616d-11eb-8d3a-1da0c7e14d85.png">
Open/Closed boxes seem to have different size/max width text:
![allright2](https://user-images.githubusercontent.com/41024075/106195769-db175100-616d-11eb-9581-775a6bd80c3d.gif)
![isthisalright](https://user-images.githubusercontent.com/41024075/106195771-dbafe780-616d-11eb-935d-853cd7cf16d6.gif)

**Comment by KatieWoe** [comment] 2021-01-28 23:51
Open/Closed boxes might have different centers?
![whatiscenter](https://user-images.githubusercontent.com/41024075/106213000-065b6980-6189-11eb-9705-dccbf6b32cfd.gif)

**Comment by jbphet** [comment] 2021-01-29 01:11
I'm not concerned about any of these.  The one just above about how the centers are off is by design, because the margins for the titles and contents have different values.  The other three seem like very minor layout issues that are super unlikely to occur since they require such long strings.

@amanda-phet - please have a look and close if you concur (or comment and assign back to me if not).

**Comment by amanda-phet** [comment] 2021-01-29 21:59
I think the different centers for the titles is acceptable, since that's just how accordion box works. I don't love it, but I think it's just how accordion box is. 

The one change I'd like to make is the "Debts" and "Assets" alignment on the tags. When the strings are really long, that space to the side looks too strange to me. So I'd like to center it roughly between the hole in the tag and the edge of the tag. @jbphet says this might just be a manual adjustment, and I'm happy to review it once he has made the tweak.

**Comment by KatieWoe** [comment] 2021-01-29 22:03
Unlikely to matter since it is unlikely to get longer, but the image on the pig in the icons can look odd with longer strings
<img width="251" alt="longpig" src="https://user-images.githubusercontent.com/41024075/106331990-218aaf80-6243-11eb-9970-b32ffed4a33b.png">

**Comment by jbphet** [comment] 2021-01-29 23:04
The label on the piggy bank doesn't matter, since in almost every case it should be a single character.  If a translator uses something longer, that's their choice, and as long as the code keeps the label within the bounds of the bank image we're fine with it.

**Comment by jbphet** [comment] 2021-01-30 00:12
The only thing from the comments above that has motivated changes is https://github.com/phetsims/number-line-operations/issues/93#issuecomment-770073118.  I'll review this with @amanda-phet and, if she is good with the changes, I'll move it to the 1.0 branch and have QA check it.

**Comment by jbphet** [comment] 2021-02-01 17:41
QA team - The only thing that needs verification on this is the appearance of the tags on the bags that are shown on the first two screens.  We want to make sure they look good by default (i.e. in English) and decent in all the string tests.  See https://github.com/phetsims/number-line-operations/issues/93#issuecomment-770073118 above if you need any more background on this.

**Comment by DevonQui** [comment] 2021-02-01 20:19
Just tested this and the appearance of the strings, as mentioned above for the price tags, is aligned as desired. Closing

**Comment by KatieWoe** [comment] 2021-02-01 22:17
Reopening with new potential string issues. Longer operation description strings can go out of bounds.
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/106524976-855de400-64a0-11eb-9bad-32239f2738eb.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/106524982-868f1100-64a0-11eb-8aa2-584880ff729f.png)

https://user-images.githubusercontent.com/41024075/106524985-8727a780-64a0-11eb-872a-2938371391af.MP4

**Comment by amanda-phet** [comment] 2021-02-01 22:28
@jbphet what should we do about this? Constrain the string width, or wrap it? Nothing?

**Comment by KatieWoe** [comment] 2021-02-01 22:32
Just realized this can be easier to see with `?dev` used. 
<img width="841" alt="longdev2" src="https://user-images.githubusercontent.com/41024075/106526358-b0493780-64a2-11eb-845f-ffe4eff0313d.png">
<img width="850" alt="longdev1" src="https://user-images.githubusercontent.com/41024075/106526360-b0e1ce00-64a2-11eb-8efe-a17db9a79ffa.png">

**Comment by jbphet** [comment] 2021-02-03 17:46
The easy fix is to reduce the `maxWidth` value for the operation description.  In fact, there is a comment in the code where the value is currently set (in `NumberLineOperationNode`) that says:
```
  // empirically determined so as to never end up partially outside the dev bounds
```

So, apparently, keeping it in dev bounds was always the goal, but we probably made some layout changes at some point and neglected to adjust this value.  I've done so now.  Here's a screenshot from the "Operations" screen.

![image](https://user-images.githubusercontent.com/3082831/106786777-2c12c380-660c-11eb-9c0a-85cd4146d194.png)

**Comment by jbphet** [comment] 2021-02-03 18:21
I verified this myself on RC.3, looks good.  Closing.

**Closed by jbphet** 2021-02-03 18:21 UTC
Labels: status:ready-for-qa, type:i18n
