### ISSUE TITLE
Multitouch: Dragging two points at once leads to wrong equation and arrow pointing to wrong place

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#80] opened 2021-01-05 23:34 UTC
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 14
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/593.
When there are number line points you can drag, and the location of one point depends on the other, moving both will lead to one point being in the wrong location. Specifically, moving the original point, while holding the resulting point still, will leave the arrow pointing to a different place and the written equation adding up to a point different than the second point.
**Steps to reproduce**
1. Go to the Generic screen
2. Add one second point
3. Use touch to grab both points
4. Move each individually while still holding the other. Observe

**Visuals**

https://user-images.githubusercontent.com/41024075/103711006-a4d22180-4f73-11eb-9360-abe9ba369bdf.MP4

![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/103711017-a865a880-4f73-11eb-94b7-d42c5d5628ef.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/103711018-a865a880-4f73-11eb-835b-f6c5dfab5131.png)

**Comment by KatieWoe** [comment] 2021-01-06 19:53
Seems to mostly/only happen if there is only one extra point, not two.

**Comment by jbphet** [comment] 2021-01-13 20:08
@KatieWoe - Since it would be difficult to make simultaneous drag of the points work correctly, I've opted for a solution where only the first grabbed point controller can be moved.  This seems to solve the reported problem.  Can you please test on master and make sure that the issue is resolved and then assign back to me with your findings?

**Comment by KatieWoe** [comment] 2021-01-13 20:29
Looks good on master.

**Comment by jbphet** [comment] 2021-01-14 19:32
I don't think that this needs to be retested when the sim goes to RC, so I'm going to close it.

**Closed by jbphet** 2021-01-14 19:32 UTC
Labels: status:fixed-awaiting-deploy, type:bug, type:multitouch
