### ISSUE TITLE
On "Generic", the max to add/subtract is not consistent

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/number-line-operations#61] opened 2020-12-24 16:46 UTC
**Test device**
Lenovo ThinkPad

**Operating System**
Win 10

**Browser**
Chrome, Firefox

**Problem description**
This is for https://github.com/phetsims/QA/issues/593
On the "Generic" screen, the max to add/subtract in the top right corner is 200, but if you move the sliders more, then you reach more than 200. If you click the up arrow again on the top right corner, it goes back to 200, so not sure if this is much of an issue. 

**Steps to reproduce**
1. Go to the "Generic" screen
2. Use the box in the top right corner to add 200 and subtract 200 (adding -200 does not work)
3. Drag the ball on the number line to move it in the left direction
4. Observe as the number goes above 200

**Visuals**
![numberline](https://user-images.githubusercontent.com/72031637/103099631-1e592f80-45c4-11eb-8f42-c4564c38a213.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.12/phet/number-line-operations_all_phet.html
Version: 1.0.0-dev.12 2020-12-23 23:50:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1707x818
Pixel Ratio: 2.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment] 2021-01-05 17:45
Adding additional odd behavior here. Once this is done, if you press the arrow that looks like it should be disabled (up in the case I recorded) the number jumps to the normal limit. If you press the active button, it increments as it normally would if it were within the limits. This may be intended, but struck me as a bit odd.
![hittinguparrowpastmax](https://user-images.githubusercontent.com/41024075/103680123-f1513900-4f42-11eb-88c8-4dcc33746701.gif)

**Comment by brooklynlash** [comment] 2021-01-05 17:51
The same thing happens if you do it in the negative direction, it goes back to the original "maximum" number

**Comment by jbphet** [comment] 2021-01-15 17:09
One of the root causes of this problem is that the number picker still fires its listener when the increment/decrement interaction is disabled.  I've logged an issue for that into scenery-phet, see link above.

We discussed the behavior in general in the 1/14/2021 design meeting, and it's a bit undesirable that it is possible to make the number shown in the number picker go beyond the limits, but it's a hard situation to avoid without preventing the user from being able to move the points in some situations, and that seems really bad.  Our conclusion was to allow the behavior, and once the `NumberPicker` issue is remedied we will consider this to be resolved.

**Comment by jbphet** [comment] 2021-01-15 23:52
I implemented a fix in common code.  It is still subject to change when reviewed, but for now the behavior seems to be fixed.  I'll have this verified on the next round of testing.

**Comment by jbphet** [comment] 2021-01-19 17:54
The changes in common code were approved, so we're good to go with this.  Once it has been verified by the QA team it can be closed.

**Comment by KatieWoe** [comment] 2021-01-19 21:42
The aspect of the issue with the picker seems fixed in dev.13. Closing

**Closed by KatieWoe** 2021-01-19 21:42 UTC
Labels: status:fixed-awaiting-deploy, type:bug
