### ISSUE TITLE
CT x should be a finite number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#26] opened 2020-11-24 17:46 UTC
```
number-line-operations : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/number-line-operations/number-line-operations_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-operations%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1606230615255%22%2C%22timestamp%22%3A1606232912623%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/assert/js/assert.js:25:13)
at VBox.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/scenery/js/nodes/Node.js:2089:17)
at VBox.setLeft (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/scenery/js/nodes/Node.js:2639:12)
at VBox.set left [as left] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/scenery/js/nodes/Node.js:2644:28)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/scenery/js/nodes/Node.js:5471:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/sherpa/lib/lodash-4.17.4.js:9359:14)
at VBox.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/scenery/js/nodes/Node.js:5458:7)
at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/scenery/js/nodes/LayoutBox.js:105:8)
at new VBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606230615255/scenery/js/nodes/VBox.js:30:13)
id: Bayes Chrome
Snapshot from 11/24/2020, 8:1
```

**Comment by jbphet** [comment] 2020-11-24 18:23
I think this was due to a push that I'd missed for the number-line-common repo.  I've now pushed it and will check back later to make sure that the problem is resolved.

**Comment by jbphet** [comment] 2020-11-24 19:23
CT has cleared up - the last two iterations were clear for this sim.  Closing.

**Closed by jbphet** 2020-11-24 19:23 UTC
Labels: type:automated-testing
