### ISSUE TITLE
Points on invisible 2nd number line are still interactive

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#43] opened 2020-12-26 20:06 UTC
Noted during #35 code review.

Running with `?showPointerAreas`, I see an odd pointer area in the Generic screen.  See the screenshot below, with arrow pointing to the pointer area in question.   

And I can interact with this invisible thing! The cursor changes on pointer over, and I can drag it around.   Labeling this issue as a bug because of the cursor change.

<img width="1022" alt="generic" src="https://user-images.githubusercontent.com/3046552/103158441-25766e00-477b-11eb-841a-cfc487ba1596.png">

**Comment by pixelzoom** [comment] 2020-12-26 20:13
Looks like this "thing" is the point on the 2nd number line.  That point should definitely not be draggable when the 2nd number line is not shown.   See screenshots below.  In the first screenshot, I (possibly accidentally, but in this case purposely) dragged the invisible point to the right.  Then I pressed the radio button to show the 2nd number line, and was surprised to find my initial point at x=4. 

<img width="1023" alt="screenshot_791" src="https://user-images.githubusercontent.com/3046552/103158530-13e19600-477c-11eb-84bc-1d1cc1772a2e.png">

<img width="1025" alt="screenshot_792" src="https://user-images.githubusercontent.com/3046552/103158532-16dc8680-477c-11eb-9a35-ee8e33a6407d.png">

**Comment by pixelzoom** [comment] 2020-12-26 20:15
This is apparently a problem with _ALL_ points on the 2nd number line.  For example, if I add points, then hide the 2nd number line, I can still (possibility accidentally) move points on the 2nd number line.  And I see the cursor change when over these invisible points.

**Comment by KatieWoe** [comment] 2021-01-05 22:44
Not just all points, but the controls for adjusting and adding points, and the eraser button.

**Comment by jbphet** [comment] 2021-01-05 22:45
I've just done some investigation on this, and there are a lot of things that are invisible and interactive on this screen, such as the expand/collapse button on the accordion box, the buttons on the carousel, and the buttons on the operation entry control.  This doesn't seem right to me, and I'm wondering if something has changed in Scenery's input functionality that is causing this.  I've got a question out on Slack about it.

**Comment by jbphet** [comment] 2021-01-05 23:13
The root of this problem was that I was only using opacity, and not visibility, to manage the appearance of the secondary number line.  I've added visibility control as well, and it seems to have fixed the problem.

**Comment by pixelzoom** [comment] 2021-01-05 23:45
As I mentioned on Slack...
> As you've probably discovered, visible pointer areas (with ?showPointerAreas) does not mean that something invisible is interactive.  The carousel (for example) shows pointer areas for all of the items, not just the ones that are visible in the carousel, since scenery apparently doesn't consider clipArea when rendering pointer areas.

So it's not the case that you can interact with every pointer area that is shown with ?showPointerAreas.

**Comment by jbphet** [comment] 2021-01-07 00:47
During a conversation on Slack, @pixelzoom suggested testing for whether interaction continues with the faded number line if that interaction starts before the fade out.  This is a multi-touch issue.  I tried it, and it does, so I have now added code to interrupt subtree input and make the number line and the associated controls unpickable when fade-out starts.

**Comment by DevonQui** [comment] 2021-01-19 19:37
I was unable to reproduce the issue. Using just the single number-line carousel on the Generic screen of the simulation, I was unable to interact with the second carousel as mentioned in this issue. Closing
<img width="1088" alt="Screen Shot 2021-01-19 at 12 33 21 PM" src="https://user-images.githubusercontent.com/72042459/105083774-a101cd00-5a52-11eb-906a-04d80487cdf4.png">

**Closed by DevonQui** 2021-01-19 19:37 UTC
Labels: status:blocks-sim-publication, status:fixed-awaiting-deploy, type:bug
